return {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    lazy = false,
    build = ':TSUpdate',
    opts = {
        ensure_installed = {
            'css',
            'dockerfile',
            'go',
            'html',
            'java',
            'json',
            'javascript',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'python',
            'ruby',
            'sql',
            'toml',
            'tsx',
            'typescript',
            'vim',
            'vue',
            'yaml',
        },
        indent = { enable = true },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = true,
        },
    },
}
